name: Check code quality
on:
  pull_request:
    branches:
      - 'master'
      - 'dev/**'
  push:
    branches:
      - 'master'
      - 'dev/**'
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test for trailing whitespace
        run: ./.github/scripts/trailing_whitespace_check.sh
      - name: Check for missing newlines
        uses: fernandrone/linelint@master
      - name: Verify YAML files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              document-start:
                present: false
              truthy:
                check-keys: false
              line-length:
                max: 120
      - name: Run Scalastyle
        run: |
          ./sbtwrapper prinz/scalastyle &&
          ./sbtwrapper prinz_mlflow/scalastyle &&
          ./sbtwrapper prinz_pmml/scalastyle &&
          ./sbtwrapper prinz_h2o/scalastyle &&
          ./sbtwrapper prinz_sample/scalastyle
