name: Check code quality
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  check_cq:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test for trailing whitespace
        uses: harupy/find-trailing-whitespace@master
      - name: Check for missing newlines
        uses: fernandrone/linelint@master
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.271'
          java-package: jdk
          architecture: x64
      - name: Download Scalastyle
        uses: wei/wget@v1
        with:
          args: -O scalastyle_2.12-1.0.0-batch.jar https://repo1.maven.org/maven2/org/scalastyle/scalastyle_2.12/1.0.0/scalastyle_2.12-1.0.0-batch.jar
      - name: Run Scalastyle
        run: java -jar scalastyle_2.12-1.0.0-batch.jar --config project/scalastyle_config.xml ./prinz/src/main/scala/
